server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: partijlid-service
          uri: http://${PARTIJLID_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/partijleden
            - Method=GET
          filters:
            - SetPath=/api/partijlid/all
        - id: partijlid-service-id
          uri: http://${PARTIJLID_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/partijlid/{id}
            - Method=GET
          filters:
            - SetPath=/api/partijlid/{id}
        - id: partijlid-service-specificName
          uri: http://${PARTIJLID_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/partijlid/naam/{naam}
            - Method=GET
          filters:
            - SetPath=/api/partijlid/naam/{naam}
        - id: partijlid-service-create
          uri: http://${PARTIJLID_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/partijlid/create
            - Method=POST
          filters:
            - SetPath=/api/partijlid/create
        - id: partijlid-service-edit
          uri: http://${PARTIJLID_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/partijlid/{id}/edit
            - Method=PUT
          filters:
            - SetPath=/api/partijlid/{id}/edit
        - id: partijlid-service-delete
          uri: http://${PARTIJLID_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/partijlid/{id}/delete
            - Method=DELETE
          filters:
            - SetPath=/api/partijlid/{id}/delete
        - id: minister-service
          uri: http://${MINISTER_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/ministers
            - Method=GET
          filters:
            - SetPath=/api/minister/all
        - id: minister-service-id
          uri: http://${MINISTER_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/minister/{id}
            - Method=GET
          filters:
            - SetPath=/api/minister/{id}
        - id: minister-service-naam
          uri: http://${MINISTER_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/minister/naam/{naam}
            - Method=GET
          filters:
            - SetPath=/api/minister/naam/{naam}
        - id: minister-service-create
          uri: http://${MINISTER_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/minister/create
            - Method=POST
          filters:
            - SetPath=/api/minister/create
        - id: minister-service-edit
          uri: http://${MINISTER_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/minister/{id}/edit
            - Method=PUT
          filters:
            - SetPath=/api/minister/{id}/edit
        - id: minister-service-delete
          uri: http://${MINISTER_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/minister/{id}/delete
            - Method=DELETE
          filters:
            - SetPath=/api/minister/{id}/delete
        - id: partij-service-all
          uri: http://${PARTIJ_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/partijen
            - Method=GET
          filters:
            - SetPath=/api/partij/all
        - id: partij-service-naam
          uri: http://${PARTIJ_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/partij/naam/{naam}
            - Method=GET
          filters:
            - SetPath=/api/partij/naam/{naam}
        - id: regering-service-all
          uri: http://${REGERING_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/regeringen
            - Method=GET
          filters:
            - SetPath=/api/regering/all
        - id: regering-service-naam
          uri: http://${REGERING_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/regering/naam/{naam}
            - Method=GET
          filters:
            - SetPath=/api/regering/naam/{naam}
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.web: DEBUG