version: '3.8'

services:
 mongo-partij:
  image: mongo:latest
  ports:
    - 27018:27017
  volumes:
    - mongodb_partij_data:/data/db

 mongo-regering:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_regering_data:/data/db
    
 mysql-partijlid:
  image: mysql:latest
  ports:
    - 3308:3306
  volumes:
    - mysql_partijlid_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-minister:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_minister_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 regering-service:
  depends_on:
    - mongo-regering
  image: jorritgeurts/regering-service:latest
  pull_policy: always
  ports:
    - 8080:8080
  links:
    - mongo-regering
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-regering

 partij-service:
  depends_on:
    - mongo-partij
  image: jorritgeurts/partij-service:latest
  pull_policy: always
  ports:
    - 8082:8082
  links:
    - mongo-partij
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-partij
   
 minister-service:
  depends_on:
    - mysql-minister
  image: jorritgeurts/minister-service:latest
  pull_policy: always
  ports:
    - 8084:8084
  links:
    - mysql-minister
  environment:
   REGERING_SERVICE_BASEURL: regering-service:8080
   PARTIJLID_SERVICE_BASEURL: partijlid-service:8081
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-minister
   MYSQL_DB_PORT: 3306

 partijlid-service:
  depends_on:
    - regering-service
    - partij-service
    - minister-service
  image: jorritgeurts/partijlid-service:latest
  pull_policy: always
  ports:
    - 8081:8081
  links:
    - regering-service
    - partij-service
    - minister-service
  environment:
   REGERING_SERVICE_BASEURL: regering-service:8080
   PARTIJ_SERVICE_BASEURL: partij-service:8082
   MINISTER_SERVICE_BASEURL: minister-service:8084
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-partijlid
   MYSQL_DB_PORT: 3306

 api-gateway:
  depends_on:
    - partijlid-service
  image: jorritgeurts/br-api-gateway:latest
  pull_policy: always
  ports:
    - 8083:8083
  links:
    - partijlid-service
  environment:
   PARTIJLID_SERVICE_BASEURL: partijlid-service:8081
   MINISTER_SERVICE_BASEURL: minister-service:8084
   PARTIJ_SERVICE_BASEURL: partij-service:8082
   REGERING_SERVICE_BASEURL: regering-service:8080

 angular-app:
  image: jorritgeurts/br-angular-app:latest
  pull_policy: always
  ports:
      - "4200:80"

volumes:
 mongodb_partij_data:
 mongodb_regering_data:
 mysql_partijlid_data:
 mysql_minister_data:
